
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public Sale Sale {get; }
    public Equip Equip {get; }
    public Test Test {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        Sale = new Sale(loader("sale"));
        Equip = new Equip(loader("equip"));
        Test = new Test(loader("test"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        Sale.ResolveRef(this);
        Equip.ResolveRef(this);
        Test.ResolveRef(this);
    }
}

}
