
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class Test
{
    private readonly System.Collections.Generic.Dictionary<int, Item.TestInfo> _dataMap;
    private readonly System.Collections.Generic.List<Item.TestInfo> _dataList;
    
    public Test(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Item.TestInfo>(n);
        _dataList = new System.Collections.Generic.List<Item.TestInfo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Item.TestInfo _v;
            _v = global::cfg.Item.TestInfo.DeserializeTestInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.IdT, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Item.TestInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<Item.TestInfo> DataList => _dataList;

    public Item.TestInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Item.TestInfo Get(int key) => _dataMap[key];
    public Item.TestInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

