
--[[------------------------------------------------------------------------------
-- <auto-generated>
--     This code was generated by a tool.
--     Changes to this file may cause incorrect behavior and will be lost if
--     the code is regenerated.
-- </auto-generated>
--]]------------------------------------------------------------------------------


local enums =
{
    ---@class AccessFlag
     ---@field public WRITE integer
     ---@field public READ integer
     ---@field public TRUNCATE integer
     ---@field public NEW integer
     ---@field public READ_WRITE integer
    ['AccessFlag'] = {   WRITE=1,  READ=2,  TRUNCATE=4,  NEW=8,  READ_WRITE=3,  };
    ---@class SaleLimitType
     ---@field public NoLimit integer @无限制
     ---@field public Day integer @每日
     ---@field public Week integer @每周
     ---@field public Month integer @每月
    ['SaleLimitType'] = {   NoLimit=1,  Day=2,  Week=3,  Month=4,  };
}

local beans = {}
    do
    ---@class Item.EquipInfo  @装备
     ---@field public ID integer
     ---@field public Name string
     ---@field public Price integer @价格
        local class = {
            { name='ID', type='integer'},
            { name='Name', type='string'},
            { name='Price', type='integer'},
        }
        beans['Item.EquipInfo'] = class
    end
    do
    ---@class Item.SaleInfo 
     ---@field public ID integer
     ---@field public Limit integer
     ---@field public Flag integer
     ---@field public name string
        local class = {
            { name='ID', type='integer'},
            { name='Limit', type='integer'},
            { name='Flag', type='integer'},
            { name='name', type='string'},
        }
        beans['Item.SaleInfo'] = class
    end
    do
    ---@class Item.TestInfo 
     ---@field public id_t integer
     ---@field public y2 table<string,integer>
     ---@field public y3 table<integer,string>
     ---@field public map_t table<integer,Item.EquipInfo>
     ---@field public array_t Item.EquipInfo[]
        local class = {
            { name='id_t', type='integer'},
            { name='y2', type='table<string,integer>'},
            { name='y3', type='table<integer,string>'},
            { name='map_t', type='table<integer,Item.EquipInfo>'},
            { name='array_t', type='Item.EquipInfo[]'},
        }
        beans['Item.TestInfo'] = class
    end
    do
    ---@class Type1 
     ---@field public a integer
     ---@field public b string
     ---@field public c boolean
        local class = {
            { name='a', type='integer'},
            { name='b', type='string'},
            { name='c', type='boolean'},
        }
        beans['Type1'] = class
    end

local tables =
{
    { name='Sale', file='sale', mode='map', index='ID', value_type='Item.SaleInfo' },
    { name='Equip', file='equip', mode='map', index='ID', value_type='Item.EquipInfo' },
    { name='Test', file='test', mode='map', index='id_t', value_type='Item.TestInfo' },
}

return { enums = enums, beans = beans, tables = tables }

