
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Item
{
public sealed partial class SaleInfo : Luban.BeanBase
{
    public SaleInfo(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        Limit = (SaleLimitType)_buf.ReadInt();
        Flag = (AccessFlag)_buf.ReadInt();
        Name = _buf.ReadString();
    }

    public static SaleInfo DeserializeSaleInfo(ByteBuf _buf)
    {
        return new Item.SaleInfo(_buf);
    }

    public readonly int ID;
    public readonly SaleLimitType Limit;
    public readonly AccessFlag Flag;
    public readonly string Name;
   
    public const int __ID__ = 1558375952;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Limit:" + Limit + ","
        + "Flag:" + Flag + ","
        + "name:" + Name + ","
        + "}";
    }
}
}

