
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class Equip
{
    private readonly System.Collections.Generic.Dictionary<int, Item.EquipInfo> _dataMap;
    private readonly System.Collections.Generic.List<Item.EquipInfo> _dataList;
    
    public Equip(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Item.EquipInfo>(n);
        _dataList = new System.Collections.Generic.List<Item.EquipInfo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Item.EquipInfo _v;
            _v = global::cfg.Item.EquipInfo.DeserializeEquipInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Item.EquipInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<Item.EquipInfo> DataList => _dataList;

    public Item.EquipInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Item.EquipInfo Get(int key) => _dataMap[key];
    public Item.EquipInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

