
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class Sale
{
    private readonly System.Collections.Generic.Dictionary<int, Item.SaleInfo> _dataMap;
    private readonly System.Collections.Generic.List<Item.SaleInfo> _dataList;
    
    public Sale(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Item.SaleInfo>(n);
        _dataList = new System.Collections.Generic.List<Item.SaleInfo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Item.SaleInfo _v;
            _v = global::cfg.Item.SaleInfo.DeserializeSaleInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Item.SaleInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<Item.SaleInfo> DataList => _dataList;

    public Item.SaleInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Item.SaleInfo Get(int key) => _dataMap[key];
    public Item.SaleInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

