
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum SaleLimitType
    {
        /// <summary>
        /// 无限制
        /// </summary>
        NoLimit = 1,
        /// <summary>
        /// 每日
        /// </summary>
        Day = 2,
        /// <summary>
        /// 每周
        /// </summary>
        Week = 3,
        /// <summary>
        /// 每月
        /// </summary>
        Month = 4,
    }

} 

