
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Item
{
/// <summary>
/// 装备
/// </summary>
public sealed partial class EquipInfo : Luban.BeanBase
{
    public EquipInfo(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        Name = _buf.ReadString();
        Price = _buf.ReadInt();
    }

    public static EquipInfo DeserializeEquipInfo(ByteBuf _buf)
    {
        return new Item.EquipInfo(_buf);
    }

    public readonly int ID;
    public readonly string Name;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
   
    public const int __ID__ = -2033195037;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "Price:" + Price + ","
        + "}";
    }
}
}

