
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Item
{
public sealed partial class TestInfo : Luban.BeanBase
{
    public TestInfo(ByteBuf _buf) 
    {
        IdT = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); Y2 = new System.Collections.Generic.Dictionary<string, int>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { string _k0;  _k0 = _buf.ReadString(); int _v0;  _v0 = _buf.ReadInt();     Y2.Add(_k0, _v0);}}
        {int n0 = _buf.ReadSize(); Y3 = new System.Collections.Generic.Dictionary<int, string>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { int _k0;  _k0 = _buf.ReadInt(); string _v0;  _v0 = _buf.ReadString();     Y3.Add(_k0, _v0);}}
        {int n0 = _buf.ReadSize(); MapT = new System.Collections.Generic.Dictionary<int, Item.EquipInfo>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { int _k0;  _k0 = _buf.ReadInt(); Item.EquipInfo _v0;  _v0 = global::cfg.Item.EquipInfo.DeserializeEquipInfo(_buf);     MapT.Add(_k0, _v0);}}
        {int __n0 = _buf.ReadSize(); ArrayT = new Item.EquipInfo[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { Item.EquipInfo __e0;__e0 = global::cfg.Item.EquipInfo.DeserializeEquipInfo(_buf); ArrayT[__index0] = __e0;}}
    }

    public static TestInfo DeserializeTestInfo(ByteBuf _buf)
    {
        return new Item.TestInfo(_buf);
    }

    public readonly int IdT;
    public readonly System.Collections.Generic.Dictionary<string, int> Y2;
    public readonly System.Collections.Generic.Dictionary<int, string> Y3;
    public readonly System.Collections.Generic.Dictionary<int, Item.EquipInfo> MapT;
    public readonly Item.EquipInfo[] ArrayT;
   
    public const int __ID__ = -1524476709;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in MapT.Values) { _e?.ResolveRef(tables); }
        foreach (var _e in ArrayT) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "idT:" + IdT + ","
        + "y2:" + Luban.StringUtil.CollectionToString(Y2) + ","
        + "y3:" + Luban.StringUtil.CollectionToString(Y3) + ","
        + "mapT:" + Luban.StringUtil.CollectionToString(MapT) + ","
        + "arrayT:" + Luban.StringUtil.CollectionToString(ArrayT) + ","
        + "}";
    }
}
}

